### ISSUE TITLE
Missing pcd.npz for kitti-360 preprocessing.

### ISSUE THREAD

**Issue by synsin0** [DNMP/DNMP#1]
Thanks for your great work! May you provide preprocessing pcd.npz code for kitti-360 dataset as in waymo processing?

**Comment by DNMP** [comment]
Sorry for the inconvenience. We generate pcd.npz for KITTI-360 dataset using [Metashape](https://www.agisoft.com/), which is a software for 3D reconstruction. We will upload pcd.npz files in near future.

**Comment by rockywind** [comment]
Hi, thank you for sharing.
How to export the pcd.npz?
![image](https://github.com/DNMP/DNMP/assets/14838781/862fe428-6d6a-4233-a9ea-717a275a37ec)

**Comment by DNMP** [comment]
@rockywind 
Hi, it seems that you only generate sparse point cloud. However, we use dense point cloud in our implementation. You may then perform dense reconstruction and export the dense point cloud as ply file. Then we load the ply file in python and save the point cloud in pcd.npz file. (You can also directly load the ply files by simply modifying the code in the [trainer](https://github.com/DNMP/DNMP/blob/b9da5a5d884b187f5e91d998736aba294b7984bf/core/trainer_geometry.py#L47C9-L49C132).)

**Comment by rockywind** [comment]
Hi, are the images to generate pcd.npz for the KITTI-360 dataset using Metashape including image_00 and image_01?

**Comment by hjhyunjinkim** [comment]
@DNMP Can you let us know when you upload the pcd.npz files?

**Comment by AmazingRoad** [comment]
@DNMP I generated a ply file for seq_1, and it is about 23MB, is this right?

**Comment by Shek-China** [comment]
> Hi, thank you for sharing. How to export the pcd.npz? ![image](https://private-user-images.githubusercontent.com/14838781/255383638-862fe428-6d6a-4233-a9ea-717a275a37ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzM0NzEsIm5iZiI6MTcxMjQ3MzE3MSwicGF0aCI6Ii8xNDgzODc4MS8yNTUzODM2MzgtODYyZmU0MjgtNmQ2YS00MjMzLWE5ZWEtNzE3YTI3NWEzN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA2NTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDZhMzZjNjc5YzJmNDFlMmE2MTk3Y2JhNzIzNzhiMWEyNTliY2Q4MzY0MWJlNTIwY2JlY2E2MGM2NGI5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5oSxeP3RmarlrTH9-Fn-pXyPOFKmMfXVmCWQiVWR4kQ)

Hi, how could you import the data to make it as the image you showed?
