### ISSUE TITLE
some question about Scene Auto-Encoder

### ISSUE THREAD

**Issue by SakuBorder** [DNMP/DNMP#11]
May I ask how you combined the lifted feature maps in the common voxel based 3D neural field in sec3.1?

**Comment by FanLu97** [comment]
Hello, thanks for your interest.
I'm not sure if I've understood your meaning correctly. In fact, we do not use voxel or lifted feature maps for rendering. Voxels are only used to initialize DNMPs for geometry training. After completing the geometry training, our renderer relies only on the features attached on mesh vertices, which is trained by the ground truth images.
