### ISSUE TITLE
Calculation of SSIM

### ISSUE THREAD

**Issue by XJay18** [DNMP/DNMP#16]
Hi, thanks for the great project!

I am a little confused about the calculation of SSIM metric in the [code](https://github.com/DNMP/DNMP/blob/ff404e2a95b09fda450fce8d52cd528a5c51100a/core/metrics.py#L14C1-L15). 

To be specific, the inputs to `ssim_fn` are two floating point numbers ranging from [0,1] (because of the sigmoid activation for rgb values). If `data_range` argument is not passed to skimage `structural_similarity` function, it assumes the data range for floating point numbers to be 2 (according to the official document [here](https://scikit-image.org/docs/stable/api/skimage.metrics.html#skimage.metrics.structural_similarity)), which is incorrect for this case. 

So, I think the code should be
```python
def ssim_fn(x, y):
    return structural_similarity(x, y, multichannel=True, data_range=1.0)
```

I would like to confirm whether I am right or not, as whether to pass `data_range` or not yields different output SSIM.

Looking forward to the reply and thanks in advance.

**Comment by FanLu97** [comment]
@XJay18 ,
Hi, we do not pass `data_range` in our evaluation for all methods. 
In fact, it was common not to pass this parameter in previous methods (e.g., [Point-NeRF](https://github.com/Xharlie/pointnerf/blob/ff10fac8081a852c2942347bc8e5cd6183159ebe/run/evaluate.py#L10C1-L11C92), [RegNeRF](https://github.com/google-research/google-research/blob/24f2a3578a6f6471ff687b4faa50e19c83c4b44d/regnerf/eval.py#L73C3-L74C58), [MVSNeRF](https://github.com/apchenstu/mvsnerf/blob/1fdf6487389d0872dade614b3cea61f7b099406e/renderer.ipynb#L268C22-L268C22), etc).

**Comment by XJay18** [comment]
Thanks for the reply!
