### ISSUE TITLE
How to get depth and normal for kitti-360

### ISSUE THREAD

**Issue by AIBUWAN** [DNMP/DNMP#4]
Great work！Thanks

FileNotFoundError: [Errno 2] No such file or directory: '/home/DNMP/data/seq_1/depth/00_0000000716.png.geometric.npy'

**Comment by FanLu97** [comment]
@AIBUWAN 
We use [colmap](https://colmap.github.io/) to obtain depth/normal maps. We also provide scripts to run colmap in the given datasets (as stated in [preprocess/README.md](https://github.com/DNMP/DNMP/blob/ff404e2a95b09fda450fce8d52cd528a5c51100a/preprocess/README.md?plain=1#L30C1-L30C257)).
